version: 2

builds:
  - id: cli
    main: ./cmd/memory
    binary: claude-memory
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  - id: server
    main: ./cmd/server
    binary: claude-memory-server
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      # Plugin manifest
      - src: .claude-plugin/plugin.json
        dst: .claude-plugin/plugin.json
      # Agents (flat directory with .md files)
      - src: agents/*.md
        dst: agents/
      # Skills (nested structure)
      - src: skills/**/SKILL.md
      # Commands (flat directory with .md files)
      - src: commands/*.md
        dst: commands/
      # Hooks (flat directory with .py files)
      - src: hooks/*.py
        dst: hooks/
      # Root config files
      - hooks.json
      # NOTE: .mcp.json excluded - ${CLAUDE_PLUGIN_ROOT} variable not resolved by Claude Code
      # Users must run: claude mcp add mark42 --scope user --transport stdio -- ~/.claude/plugins/local/claude-memory/bin/claude-memory-server
      - README.md
      - LICENSE

brews:
  - name: claude-memory
    repository:
      owner: mfenderov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/mfenderov/claude-memory
    description: "Local, privacy-first RAG memory system for Claude Code"
    license: MIT
    directory: Formula
    install: |
      bin.install "claude-memory"
      bin.install "claude-memory-server"

      # Install plugin assets to share directory (Homebrew-managed)
      (share/"claude-memory").install ".claude-plugin"
      (share/"claude-memory").install "agents"
      (share/"claude-memory").install "skills"
      (share/"claude-memory").install "commands"
      (share/"claude-memory").install "hooks"
      (share/"claude-memory").install "hooks.json"
    post_install: |
      # Create Claude Code plugin directory structure
      plugin_dir = Pathname.new(Dir.home) / ".claude" / "plugins" / "local" / "claude-memory"

      # Clean up existing installation (handles upgrades)
      plugin_dir.rmtree if plugin_dir.exist?
      plugin_dir.mkpath
      (plugin_dir / "bin").mkpath

      # Symlink plugin files from share directory
      ln_s share/"claude-memory"/".claude-plugin", plugin_dir/".claude-plugin"
      ln_s share/"claude-memory"/"agents", plugin_dir/"agents"
      ln_s share/"claude-memory"/"skills", plugin_dir/"skills"
      ln_s share/"claude-memory"/"commands", plugin_dir/"commands"
      ln_s share/"claude-memory"/"hooks", plugin_dir/"hooks"
      ln_s share/"claude-memory"/"hooks.json", plugin_dir/"hooks.json"

      # Symlink binaries
      ln_s bin/"claude-memory", plugin_dir/"bin"/"claude-memory"
      ln_s bin/"claude-memory-server", plugin_dir/"bin"/"claude-memory-server"

      # Ensure memory database directory exists (but NEVER touch the database itself)
      memory_dir = Pathname.new(Dir.home) / ".claude"
      memory_dir.mkpath

      # Try to register MCP server (may fail in Homebrew sandbox - see caveats)
      server_path = plugin_dir / "bin" / "claude-memory-server"
      system "claude", "mcp", "add", "mark42", "--scope", "user", "--transport", "stdio", "--", server_path.to_s
    caveats: |
      Claude Memory plugin installed!

      ══════════════════════════════════════════════════════════════
      YOUR MEMORY IS SAFE
      ══════════════════════════════════════════════════════════════

      Database location: ~/.claude/memory.db

      This file contains YOUR knowledge graph and is NEVER touched by
      brew install, upgrade, or uninstall. Your memories persist forever.

      ══════════════════════════════════════════════════════════════

      Plugin location: ~/.claude/plugins/local/claude-memory/

      ══════════════════════════════════════════════════════════════
      IMPORTANT: Register the MCP server (one-time setup)
      ══════════════════════════════════════════════════════════════

      Run this command to enable the "mark42" memory server:

        claude mcp add mark42 --scope user --transport stdio -- \\
          ~/.claude/plugins/local/claude-memory/bin/claude-memory-server

      Then restart Claude Code. The hooks will fire automatically.

      ══════════════════════════════════════════════════════════════

      Available commands: /init, /status, /sync, /calibrate

      Verify installation:
        claude-memory version
        claude-memory stats

      Backup recommendation:
        cp ~/.claude/memory.db ~/.claude/memory.db.backup

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
